### ISSUE TITLE
If no demands in my selected area, show demands near me...

### ISSUE THREAD

**Issue by craigmcginley** [goinvo/ListofDemands#20]
If there are no demands in my immediate area, then indicate there are no demands and that I can create a new demand for my area, but then under that show a list of demands near me.

If there are 5 or less in my area, show the ~5 then show demands near me underneath.

"Demands near me" can be defined as always looking one level "up" the area parent order. Like so (also open to feedback on this logic):
- Municipality's demands, or if empty then
- County's demands, or if empty then
- State demands, or if empty then
- Any demands in my state (even for "foreign" counties/munis), or if empty then
- ? (In the future, possibly all of USA)

**Comment by fermion** [comment]
I've added the backend implementation of this in #72. While it's working as expected we need direction on what the UI should look like/say, etc., when the search falls back from municipality to county to state. @craigmcginley is to get direction there. Let's open a new ticket for style/UX updates so we can enable the `:fancy_search` feature flag.
