### ISSUE TITLE
In mobile the scoped area isn't shown in the header.

### ISSUE THREAD

**Issue by fermion** [goinvo/ListofDemands#24]
![demands](https://user-images.githubusercontent.com/2804/39376440-b65bca3e-4a1f-11e8-84a9-a28a3f663a8c.gif)

I'd expect the header text to show the name of the municipality/county/state when scoped.

**Comment by craigmcginley** [comment]
Linked to #18

**Comment by fermion** [comment]
Totes a dupe of #18 my bad.
