### ISSUE TITLE
Need "Other" in topics

### ISSUE THREAD

**Issue by jsonin** [goinvo/ListofDemands#30]
![image](https://user-images.githubusercontent.com/106187/39648540-835bd89a-4fb0-11e8-826f-10d09aa0ef94.png)

**Comment by craigmcginley** [comment]
@jsonin Have both <empty> + 'Other' as options? Or add 'Other' and don't allow the topic to be empty?

**Comment by jsonin** [comment]
Allow it to be not-required.
Add other on the bottom... that sorta works?

**Comment by craigmcginley** [comment]
Done in #35
