### ISSUE TITLE
Unique, public demands of a user

### ISSUE THREAD

**Issue by jsonin** [goinvo/ListofDemands#73]
Need every person’s personal LoD to be accessible, and public.

Senator X’s demands.
My demands.
Councilwoman’s demands.
Ralph’s demands.

Name should be title size... people need to instantly know whose LoD it is.

URL with /me doesn’t work.

**Comment by craigmcginley** [comment]
Done in #77 

Going to additionally refactor this to remove /me, using same URL for "Me" and "public" demands pages
